modLoader = "javafml"
loaderVersion = "51,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raised"
version = "${version}"
displayName = "Raised"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Raises the hotbar so the selector is not cut off!
'''

[[dependencies.raised]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "forge"
mandatory = true
versionRange = "[51,)"
ordering = "NONE"
side = "CLIENT"