modLoader = "javafml"
loaderVersion = "1,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raised"
version = "${version}"
displayName = "Raised"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Raises the hotbar so the selector is not cut off!
'''

[[mixins]]
config = "raised.mixins.json"

[[dependencies.raised]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raised]]
modId = "neoforge"
type = "required"
versionRange = "[20.5,)"
ordering = "NONE"
side = "CLIENT"