modLoader = "javafml"
loaderVersion = "41,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "raisedxdetailarmorbar"
version = "${version}"
displayName = "Raised x Detail Armor Bar"
displayTest = "IGNORE_ALL_VERSION"
displayURL = "https://github.com/yurisuika/Raised"
issueTrackerURL = "https://github.com/yurisuika/Raised/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Adds support for Detail Armor Bar to Raised!
'''

[[dependencies.raisedxdetailarmorbar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,1.19.2]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxdetailarmorbar]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxdetailarmorbar]]
modId = "raised"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.raisedxdetailarmorbar]]
modId = "detailab"
mandatory = false
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"